#####################################################################################
# Product: ADempiere gRPC Server                                                    #
# Copyright (C) 2020 Edwin Betancourt                                               #
# Contributor(s): Edwin Betancourt EdwinBetanc0urt@outlook.com                      #
# This program is free software: you can redistribute it and/or modify              #
# it under the terms of the GNU General Public License as published by              #
# the Free Software Foundation, either version 3 of the License, or                 #
# (at your option) any later version.                                               #
# This program is distributed in the hope that it will be useful,                   #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                    #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                     #
# GNU General Public License for more details.                                      #
# You should have received a copy of the GNU General Public License                 #
# along with this program.  If not, see <https://www.gnu.org/licenses/>.            #
#####################################################################################
version: "2.1"

services:
  access-server:
    extends:
      file: access-server/docker-compose.yaml
      service: access-grpc-server

  dictionary-server:
    extends:
      file: dictionary-server/docker-compose.yaml
      service: dictionary-grpc-server

  business-data-server:
    extends:
      file: business-server/docker-compose.yaml
      service: business-grpc-server

  enrollment-server:
    extends:
      file: enrollment-server/docker-compose.yaml
      service: enrollment-grpc-server

volumes:
  access-server:
    driver: local
  dictionary-server:
    driver: local
  business-data-server:
    driver: local
  enrollment-server:
    driver: local
